POST http://localhost:3030/postBlog
Content-Type: application/json

{
    "category": "Technology",
    "title": "Introduction to Node.js",
    "cover": "https://example.com/nodejs-cover.jpg",
    "readTime": 5,
    "author": {
        "name": "John Doe",
        "cover": "https://example.com/author-avatar.jpg"
    },
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dapibus massa ut tortor pharetra, quis faucibus mi convallis. Fusce vehicula vestibulum justo, ac malesuada felis tincidunt eu. Sed in urna ligula."
}

####

POST http://localhost:3030/signup
Content-Type: application/json

{
    "email": "gine@gmail.com",
    "password": "hello234"
}


####

GET http://localhost:3030/users