POST http://localhost:3030/postBlog
Content-Type: application/json

{
    "category": "Technology",
    "title": "Introduction to Node.js",
    "cover": "https://example.com/nodejs-cover.jpg",
    "readTime": 5,
    "author": {
        "name": "John Doe",
        "cover": "https://example.com/author-avatar.jpg"
    },
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dapibus massa ut tortor pharetra, quis faucibus mi convallis. Fusce vehicula vestibulum justo, ac malesuada felis tincidunt eu. Sed in urna ligula."
}

####

GET http://localhost:3030/getBlogs

####

GET http://localhost:3030/getBlogs/660582f9c84e43ef781e1455/comments


####

GET http://localhost:3030/getBlogs/660582f9c84e43ef781e1455/comments/6605809f3ac715bcddbde5fd


####

PATCH http://localhost:3030/updateBlog/66059fb0dd177d5c206f8c11/comments/66059ff2dd177d5c206f8c14
Content-type: application/json

{
    "user": "Val",
    "comment": "Pretty good"
}

####

POST http://localhost:3030/signup
Content-Type: application/json

{
    "email": "ginevra@prova.com",
    "password": "hello"
}

####

GET http://localhost:3030/users

####

GET http://localhost:3030/user/ginevra@prova.com
